name: pre-commit
on: [pull_request]

permissions:
  contents: read # for checkout

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    container:
      image: bcochofel/terraform-tools:1.6.1
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory '*'
      - run: pre-commit run --all-files -v || cat /github/home/.cache/pre-commit/pre-commit.log
