name: pre-commit
on: [pull_request]

permissions:
  contents: read # for checkout

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    container:
      image: bcochofel/terraform-tools:1.6.0
    steps:
      - uses: actions/checkout@v4
      - run: ls -al
      - run: pre-commit run --all-files
