name: Terraform
on: [pull_request]

permissions:
  contents: read # for checkout

jobs:
  fmt:
    name: terraform init
    runs-on: ubuntu-latest
    container:
      image: bcochofel/terraform-tools:1.6.0
    steps:
      - uses: actions/checkout@v4
      - run: terraform -chdir=infrastructure/ init
